ccflags-y += -DDEBUG
ccflags-y += -Werror

snd-soc-hda-sst-dsp-objs := soc-hda-sst-debug.o soc-hda-sst-dsp.o soc-hda-sst-ipc.o\
soc-hda-sst-skl.o soc-hda-sst-bxt.o

# SST DSP Library
obj-$(CONFIG_SND_SOC_HDA_SST_DSP) += snd-soc-hda-sst-dsp.o
