diff a/sound/soc/Makefile b/sound/soc/Makefile	(rejected hunks)
@@ -1,3 +1,5 @@
+ccflags-y += -DDEBUG
+
 snd-soc-core-objs := soc-core.o soc-dapm.o soc-jack.o soc-cache.o soc-utils.o
 snd-soc-core-objs += soc-pcm.o soc-compress.o soc-io.o soc-fw.o
 
