snd-soc-hda-bus-objs := soc-hda-bus.o

snd-soc-hda-intel-objs := soc-hda-core.o soc-hda-pcm.o

# common driver
obj-$(CONFIG_SND_SOC_HDA_BUS) += snd-soc-hda-bus.o
obj-$(CONFIG_SND_SOC_HDA_INTEL) += snd-soc-hda-intel.o
